learning_log/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('users/', include('users.urls', namespace='users')),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    path('admin/', admin.site.urls),
]

learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Topics page
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'users'

urlpatterns = [
    # Login page
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    # Logout page
    path('logout/', views.logout_user, name='logout'),
    # Registration page
     path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    '''A topic the user is learning about'''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        """Return a string representation of the model."""
        return self.text
    
class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = "entries"
        
    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) >= 50:
            return self.text[:50] + "..."
        
        

    

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """The home page for learning_log"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = get_object_or_404(Topic, id=topic_id, owner=request.user)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    else:
        form = TopicForm()
    
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = get_object_or_404(Topic, id=topic_id, owner=request.user)
    if request.method == 'POST':
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    else:
        form = EntryForm()
    
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic
    if request.method == 'POST':
        form = EntryForm(request.POST, instance=entry)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    else:
        form = EntryForm(instance=entry)
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_user(request):
    logout(request)
    return redirect('learning_logs:index')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(request=request, username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return redirect('learning_logs:index')
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'users/register.html', context)

def logout_user(request):
    logout(request)
    return redirect('learning_logs:index')

learning_logs/templates/learning_logs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Learning Log</title>
        <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
        {% load bootstrap3 %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% bootstrap_css %}
    </head>
    <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarNav">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Home</a>
            </div>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'users:logout' %}">Log out</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">Register</a></li>
                        <li><a href="{% url 'users:login' %}">Log in</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div>

    {% bootstrap_javascript %}
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry:</p>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<div class='jumbotron'>
    <h1>Track your learning.</h1> 
</div>
{% endblock header %}

{% block content %}
<h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own Learning Log, and list the topics you're learning about.
</h2>
<h2>
    Whenever you learn something new about a topic, make an entry 
    summarizing what you've learned.
</h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" name="submit" class="btn btn-primary">Add entry</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">Add topic</button>
    {% endbuttons %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
<h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
{% for entry in entries %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>
            {{ entry.date_added|date:'M d, Y H:i' }}
            <small>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
            </small>
        </h3>
    </div>
    <div class="panel-body">
        {{ entry.text|linebreaks }}
    </div>
</div> <!-- panel -->
{% empty %}
<li>
    There are no entries for this topic yet.
</li>
{% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h1>Topics</h1>
{% endblock header %}

{% block content %}
<ul>
    {% for topic in topics %}
    <li>
        <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
    </li>
    {% empty %}
    <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

<h3><a href="{% url 'learning_logs:new_topic' %}" class="btn btn-primary">Add new topic</a></h3>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
<form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}

    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Log in</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <form method="post" action="{% url 'users:register' %}" class="form-horizontal">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">{{ field.label_tag }}</label>
                <div class="col-sm-10">
                    {{ field }}
                </div>
            </div>
        {% endfor %}

        <div class="form-group row">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Register</button>
                <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
            </div>
        </div>
    </form>
{% endblock content %}